name: Job workflow status
on:
  schedule:
    # Runs every day
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: display job status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

          
